version: '3.3'
services:
  client:
    environment:
      - GET_HOSTS_FROM=dns
    image: "fedchim-pytorch:latest"
    build:
      context: .
    working_dir: /app
    command: /bin/bash -c "fedn run client -in client.yaml"
    volumes:
      - ./data/client/:/app/data
      - ./client.yaml:/app/client.yaml
